export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  SESSION_REVOKED: "SESSION_REVOKED",

  ADMIN_CREATED: "ADMIN_CREATED",
  ADMIN_UPDATED: "ADMIN_UPDATED",
  ADMIN_DISABLED: "ADMIN_DISABLED",
  ADMIN_ENABLED: "ADMIN_ENABLED",
  ROLE_ASSIGNED: "ROLE_ASSIGNED",
  ROLE_REMOVED: "ROLE_REMOVED",
  ROLE_CREATED: "ROLE_CREATED",
  ROLE_UPDATED: "ROLE_UPDATED",

  AUTHORIZATION_DENIED: "AUTHORIZATION_DENIED",

  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",

  DEVICE_UPDATED: "DEVICE_UPDATED",
  DEVICE_STATUS_CHANGED: "DEVICE_STATUS_CHANGED",

  SUPPORT_CASE_CREATED: "SUPPORT_CASE_CREATED",
  SUPPORT_CASE_UPDATED: "SUPPORT_CASE_UPDATED",
  SUPPORT_CASE_STATUS_CHANGED: "SUPPORT_CASE_STATUS_CHANGED",
  SUPPORT_CASE_ASSIGNED: "SUPPORT_CASE_ASSIGNED",
  SUPPORT_CASE_UNASSIGNED: "SUPPORT_CASE_UNASSIGNED",
  SUPPORT_CASE_RESOLVED: "SUPPORT_CASE_RESOLVED",
  SUPPORT_CASE_CLOSED: "SUPPORT_CASE_CLOSED",
  SUPPORT_CASE_NOTE_ADDED: "SUPPORT_CASE_NOTE_ADDED",

  APP_ISSUE_CREATED: "APP_ISSUE_CREATED",
  APP_ISSUE_UPDATED: "APP_ISSUE_UPDATED",
  APP_ISSUE_STATUS_CHANGED: "APP_ISSUE_STATUS_CHANGED",
  APP_ISSUE_ASSIGNED: "APP_ISSUE_ASSIGNED",
  APP_ISSUE_UNASSIGNED: "APP_ISSUE_UNASSIGNED",
  APP_ISSUE_RESOLVED: "APP_ISSUE_RESOLVED",

  CAMPAIGN_CREATED: "CAMPAIGN_CREATED",
  CAMPAIGN_UPDATED: "CAMPAIGN_UPDATED",
  CAMPAIGN_SCHEDULED: "CAMPAIGN_SCHEDULED",
  CAMPAIGN_ACTIVATED: "CAMPAIGN_ACTIVATED",
  CAMPAIGN_COMPLETED: "CAMPAIGN_COMPLETED",
  CAMPAIGN_CANCELLED: "CAMPAIGN_CANCELLED",

  REWARD_CREATED: "REWARD_CREATED",
  REWARD_UPDATED: "REWARD_UPDATED",
  REWARD_ACTIVATED: "REWARD_ACTIVATED",
  REWARD_PAUSED: "REWARD_PAUSED",
  REWARD_RESUMED: "REWARD_RESUMED",
  REWARD_EXPIRED: "REWARD_EXPIRED",
  REWARD_CANCELLED: "REWARD_CANCELLED",

  RISK_SIGNAL_CREATED: "RISK_SIGNAL_CREATED",
  RISK_SIGNAL_STATUS_CHANGED: "RISK_SIGNAL_STATUS_CHANGED",

  RISK_CASE_CREATED: "RISK_CASE_CREATED",
  RISK_CASE_UPDATED: "RISK_CASE_UPDATED",
  RISK_CASE_ASSIGNED: "RISK_CASE_ASSIGNED",
  RISK_CASE_UNASSIGNED: "RISK_CASE_UNASSIGNED",
  RISK_CASE_STATUS_CHANGED: "RISK_CASE_STATUS_CHANGED",
  RISK_CASE_SEVERITY_CHANGED: "RISK_CASE_SEVERITY_CHANGED",
  RISK_CASE_NOTE_ADDED: "RISK_CASE_NOTE_ADDED",
  RISK_CASE_EVIDENCE_ADDED: "RISK_CASE_EVIDENCE_ADDED",
  RISK_CASE_DECISION_RECORDED: "RISK_CASE_DECISION_RECORDED",
  RISK_CASE_RESOLVED: "RISK_CASE_RESOLVED",
  RISK_CASE_CLOSED: "RISK_CASE_CLOSED",

  SECURITY_EVENT_CREATED: "SECURITY_EVENT_CREATED",
  SECURITY_EVENT_STATUS_CHANGED: "SECURITY_EVENT_STATUS_CHANGED",

  SECURITY_CASE_CREATED: "SECURITY_CASE_CREATED",
  SECURITY_CASE_UPDATED: "SECURITY_CASE_UPDATED",
  SECURITY_CASE_ASSIGNED: "SECURITY_CASE_ASSIGNED",
  SECURITY_CASE_UNASSIGNED: "SECURITY_CASE_UNASSIGNED",
  SECURITY_CASE_STATUS_CHANGED: "SECURITY_CASE_STATUS_CHANGED",
  SECURITY_CASE_SEVERITY_CHANGED: "SECURITY_CASE_SEVERITY_CHANGED",
  SECURITY_CASE_NOTE_ADDED: "SECURITY_CASE_NOTE_ADDED",
  SECURITY_CASE_EVIDENCE_ADDED: "SECURITY_CASE_EVIDENCE_ADDED",
  SECURITY_CASE_RESOLVED: "SECURITY_CASE_RESOLVED",
  SECURITY_CASE_CLOSED: "SECURITY_CASE_CLOSED",

  SECURITY_ACTION_REQUESTED: "SECURITY_ACTION_REQUESTED",
  SECURITY_ACTION_APPROVED: "SECURITY_ACTION_APPROVED",
  SECURITY_ACTION_REJECTED: "SECURITY_ACTION_REJECTED",
  SECURITY_FORCE_LOGOUT: "SECURITY_FORCE_LOGOUT",
  SECURITY_SESSIONS_REVOKED: "SECURITY_SESSIONS_REVOKED",

  // Distinct from ADMIN_CREATED/ROLE_CREATED etc. above (the original Phase 1
  // surface) so an audit reviewer can tell which API surface made the change.
  ADMINISTRATION_ADMIN_CREATED: "ADMINISTRATION_ADMIN_CREATED",
  ADMINISTRATION_ADMIN_UPDATED: "ADMINISTRATION_ADMIN_UPDATED",
  ADMINISTRATION_ADMIN_ENABLED: "ADMINISTRATION_ADMIN_ENABLED",
  ADMINISTRATION_ADMIN_DISABLED: "ADMINISTRATION_ADMIN_DISABLED",
  ADMINISTRATION_ADMIN_ROLE_ASSIGNED: "ADMINISTRATION_ADMIN_ROLE_ASSIGNED",
  ADMINISTRATION_ADMIN_ROLE_REMOVED: "ADMINISTRATION_ADMIN_ROLE_REMOVED",
  ADMINISTRATION_ADMIN_SESSIONS_REVOKED: "ADMINISTRATION_ADMIN_SESSIONS_REVOKED",

  ADMINISTRATION_ROLE_CREATED: "ADMINISTRATION_ROLE_CREATED",
  ADMINISTRATION_ROLE_UPDATED: "ADMINISTRATION_ROLE_UPDATED",
  ADMINISTRATION_ROLE_ENABLED: "ADMINISTRATION_ROLE_ENABLED",
  ADMINISTRATION_ROLE_DISABLED: "ADMINISTRATION_ROLE_DISABLED",
  ADMINISTRATION_ROLE_PERMISSIONS_UPDATED: "ADMINISTRATION_ROLE_PERMISSIONS_UPDATED",

  APPROVAL_CREATED: "APPROVAL_CREATED",
  APPROVAL_APPROVED: "APPROVAL_APPROVED",
  APPROVAL_REJECTED: "APPROVAL_REJECTED",
  APPROVAL_CANCELLED: "APPROVAL_CANCELLED",
  APPROVAL_EXPIRED: "APPROVAL_EXPIRED",
  APPROVAL_EXECUTED: "APPROVAL_EXECUTED",
  APPROVAL_EXECUTION_FAILED: "APPROVAL_EXECUTION_FAILED",

  // Read-audit of a provider-backed sensitive lookup. Metadata never holds KYC data.
  KYC_VIEWED: "KYC_VIEWED",
  // Same convention for beneficiaries. Metadata never holds beneficiary data.
  BENEFICIARY_VIEWED: "BENEFICIARY_VIEWED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
